### PR TITLE
Added media field to Product fragment

### PR DESCRIPTION
**Pull request by jessej-luo**
### Asana Task
https://app.asana.com/0/1207747047277688/1207787267252212/f

### Summary
We would like to support video media on a Product Details page. To do so, we can use the media field and extract the video/image similar to how we did for metafields.

### Performed Testing
`npm run build
`npm link @hellojuniper-com/shopify-buy` in juniper-react

I also verified with this change [here](https://github.com/hellojuniper-com/juniper-react/pull/415) to see that everything works 

Go to strawberry eggdog plush on eggdog and verify the following in the product graphql response:

```
            "media": {
                "pageInfo": {
                    "hasNextPage": false,
                    "hasPreviousPage": false
                },
                "edges": [
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc4OTAyODE1OTY3OSwibGFzdF92YWx1ZSI6MX0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28789028159679",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group18.jpg?v=1715785559",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group18.jpg?v=1715785559",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28794623295679"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTc5NTU0NjMwMywibGFzdF92YWx1ZSI6Mn0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779795546303",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/main.jpg?v=1715785559",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/main.jpg?v=1715785559",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785380458687"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNDgwNTk1MSwibGFzdF92YWx1ZSI6M30=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779714805951",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group3.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group3.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299587263"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNDk2OTc5MSwibGFzdF92YWx1ZSI6NH0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779714969791",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group1.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group1.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299751103"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNDkzNzAyMywibGFzdF92YWx1ZSI6NX0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779714937023",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group2.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group2.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299718335"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNTAwMjU1OSwibGFzdF92YWx1ZSI6Nn0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779715002559",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group6.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group6.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299783871"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNDkwNDI1NSwibGFzdF92YWx1ZSI6N30=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779714904255",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group4.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group4.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299685567"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNDgzODcxOSwibGFzdF92YWx1ZSI6OH0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779714838719",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group5.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group5.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299620031"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc3OTcxNTAzNTMyNywibGFzdF92YWx1ZSI6OX0=",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28779715035327",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group7.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group7.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28785299816639"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODc4OTI4NTg3OTk5OSwibGFzdF92YWx1ZSI6MTB9",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28789285879999",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group21.jpg?v=1715357817",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/Group21.jpg?v=1715357817",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28794896122047"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyODg0MDM5NzcwMTMxMSwibGFzdF92YWx1ZSI6MTF9",
                        "node": {
                            "__typename": "MediaImage",
                            "id": "gid://shopify/MediaImage/28840397701311",
                            "image": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/strawberry-eggdog-spin-1080x1960_1.gif?v=1715970127",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/strawberry-eggdog-spin-1080x1960_1.gif?v=1715970127",
                                "altText": null,
                                "id": "gid://shopify/ImageSource/28846150058175"
                            }
                        }
                    },
                    {
                        "cursor": "eyJsYXN0X2lkIjoyNTIxMDEzNTIxNjMxOSwibGFzdF92YWx1ZSI6bnVsbH0=",
                        "node": {
                            "__typename": "Video",
                            "id": "gid://shopify/Video/25210135216319",
                            "previewImage": {
                                "originalSrc": "https://cdn.shopify.com/s/files/1/1796/6745/files/preview_images/c3ff3f205e6440d39f2188138d6a1bc4.thumbnail.0000000.jpg?v=1655408037",
                                "url": "https://cdn.shopify.com/s/files/1/1796/6745/files/preview_images/c3ff3f205e6440d39f2188138d6a1bc4.thumbnail.0000000.jpg?v=1655408037"
                            },
                            "sources": [
                                {
                                    "format": "mp4",
                                    "url": "https://junipersales.myshopify.com/cdn/shop/videos/c/vp/c3ff3f205e6440d39f2188138d6a1bc4/c3ff3f205e6440d39f2188138d6a1bc4.HD-1080p-7.2Mbps.mp4",
                                    "height": 1080,
                                    "width": 832
                                },
                                {
                                    "format": "m3u8",
                                    "url": "https://junipersales.myshopify.com/cdn/shop/videos/c/vp/c3ff3f205e6440d39f2188138d6a1bc4/c3ff3f205e6440d39f2188138d6a1bc4.m3u8",
                                    "height": 1080,
                                    "width": 832
                                },
                                {
                                    "format": "mp4",
                                    "url": "https://junipersales.myshopify.com/cdn/shop/videos/c/vp/c3ff3f205e6440d39f2188138d6a1bc4/c3ff3f205e6440d39f2188138d6a1bc4.HD-720p-4.5Mbps.mp4",
                                    "height": 720,
                                    "width": 554
                                },
                                {
                                    "format": "mp4",
                                    "url": "https://junipersales.myshopify.com/cdn/shop/videos/c/vp/c3ff3f205e6440d39f2188138d6a1bc4/c3ff3f205e6440d39f2188138d6a1bc4.SD-480p-1.5Mbps.mp4",
                                    "height": 480,
                                    "width": 370
                                }
                            ]
                        }
                    }
                ]
            },
```

### CODE REVIEW

**Review by rmawong — DISMISSED** [review]
Looks good! Before we bump the dependency version in `juniper-react`, can you take a look at whether the GQL response payloads increases drastically as a result of this? If so, we may want to consider removing `images`

**Comment by jessej-luo** [comment]
@rmawong Now that you bring it up, I'm thinking about a couple different things here:

1. We have a `ProductFragmentSimplified` that we use for the CollectionView. Currently we're getting the [images](https://github.com/hellojuniper-com/shopify-buy-sdk/blob/e5531a68d2e78ff87272c9569cf8e7a9cab491e1/src/graphql/ProductFragmentSimplified.graphql#L12), specifically 2 of them so that we can hover and see the second one. We could potentially change this to `media`, but if we have a video as the first element, it might be weird to have that as the cover for the `CollectionView`. I think it might make sense to still retrieve images for the `ProductFragmentSimplified`

2. We can definitely just migrate to `media` and bump this version/make the changes at the same time. Don't think we need `images`.

3. I need to also update the types so that we're exposing `media` and removing `images`

**Comment by rmawong** [comment]
@jessej-luo those all make sense. For the first point, I'm good with keeping images on the simplified fragment, however, one other option to consider is use `media` but filter out videos from the first two elements in the list (either in the SDK or on the client itself). Not sure if this option is worth the effort though.

**Comment by jessej-luo** [comment]
Sounds good! I revised this PR a bit to change naming conventions and also simplified a couple different things.

I retained images on collections and made Media have image and video types.

**Review by rmawong — APPROVED** [review]

**Pull request merged**
